faros-ai/faros-js-client

.github/workflows/release.yml

A build step is needed, otherwise the `lib` directory with the library source is not created.
See https://github.com/faros-ai/faros-js-client/actions/runs/3396552819/jobs/5647744672
It only copies a couple of resource files, package.json, README and LICENSE into the npm package
> Fix [#1]() 

Add build step

---

src/graphql/graphql.ts
src/index.ts
test/__snapshots__/graphql.test.ts.snap
test/graphql.test.ts
test/resources/schema-v2.gql

Add functions to create incremental queries for all models in a schema
Reuses the `buildIncrementalQueryV1/V2` functionality with 2 minor changes:
- Introduces a param `avoidCollisions` to control whether to avoid field name collisions when flattening (not needed for my use case, left the current behavior as default).
- Adds the `metadata {refreshedAt}` to the selections in V1.
> Fix [#1]() 

Add functions to create incremental queries for all models in a schema

---

package-lock.json
package.json

Since [we import and invoke functions](https://github.com/faros-ai/faros-js-client/blob/9ba10618204a654f26c15879ad96477fd76e231b/src/graphql/hasura-schema-loader.ts#L8) from the `ts-essentials` library, it needs to be a runtime dependency. Otherwise we'll get runtime errors. For example, in the feeds `release` job:
```
Error: Cannot find module 'ts-essentials'
Require stack:
- /tmp/mock-data-feed-1670638687176/node_modules/faros-js-client/lib/graphql/hasura-schema-loader.js
- /tmp/mock-data-feed-1670638687176/node_modules/faros-js-client/lib/index.js
- /tmp/mock-data-feed-1670638687176/node_modules/faros-feeds-sdk/lib/feed.js
- /tmp/mock-data-feed-1670638687176/node_modules/faros-feeds-sdk/lib/index.js
- /tmp/mock-data-feed-1670638687176/lib/index.js
- …
```

Make ts-essentials a runtime dependency

---

src/client.ts

Sync Faros client implementation with canonical-reports:
- Adds `createGraph` and `addCanonicalModels`
Does not add [encodedGraphName](https://github.com/faros-ai/canonical-reports/blob/5a4bbdd83be2098e50fa8c2194597f3f07729d77/src/clients/faros.ts#L46) since I wasn't sure it'd be needed outside of `canonical-reports`. I need your input here @eskrm @ted-faros 
I also didn't add the [tenant](https://github.com/faros-ai/canonical-reports/blob/5a4bbdd83be2098e50fa8c2194597f3f07729d77/src/clients/faros.ts#L23) property since it's never used. There's also a `tenant` function in the current implementation (I guess it is derived from the API key?).
The last remaining difference between the client in this library vs the client in `canonical-reports` is that we take a `graph` param for all the …

Sync Faros client implementation with canonical-reports

---

src/adapter/index.ts

Accepts `args` param. This is needed for example for incremental queries where we need to specify `from` and `to`.
> Fix [#1]() 

Accept args param

---

src/adapter/index.ts
test/adapter.test.ts
test/tsconfig.json

There's [one](https://github.com/faros-ai/aion/blob/main/resources/flows/tags/application-commit.yml#L39) flow that uses `first` in a nested field. This will convert it to `limit`.

FAI-3724: rename first field argument to limit in adapter

---

src/graphql/graphql.ts
test/resources/schemas/schema-v2.gql
test/resources/schemas/v2_schema_for_adapter_test.gql
test/resources/schemas/v2_schema_for_fk_exclusion_test.gql
test/resources/schemas/v2_schema_for_pk_test.gql

Use farosModel field in table comment as marker for v2 model type

FAI-4880: Fix isV2ModelType

---

src/client.ts
src/graphql/graphql.ts
test/resources/queries/paginated-commits-offset-limit-v2.gql

Add tie-breaker `order_by` to ensure sort is stable.  Without this, pagination gives erratic results.

FAI-4951: Graph-to-graph Copy Validation

---

src/client.ts
src/types.ts
test/client.test.ts

Add `phantoms` query parameter for v2 queries with default of `Phantom.IncludeNestedOnly`.

FAI-5090: add new phantoms enum to replicate v1 default

---

scripts/load-schema.js
src/graphql/hasura-schema-loader.ts
src/graphql/schema.ts

Adjustments to `HasuraSchemaLoader` to handle "reverse object relationships".  
[Hasura #48](https://github.com/faros-ai/hasura/pull/48) will replace some array relationships having unique constraints with object relationships pointing the in the reverse direction (i.e. an object relationship where FK is on the remote table).  This change in metadata impacts the schema loader.  The net effect of this PR is to leave schema unchanged by reading equivalent information from the newly introduced reverse object relationships.
This PR has been tested for against Faros CE and verified to produce no change in the schema.  Similarly, it was tested against the new SaaS schema and shown to produce no change.

FAI-5080: v2 flow author ids are unknown 

---

src/graphql/graphql.ts
test/graphql.test.ts

Ensure pagination schemes for extract and flow queries are consistent.
We use pagination in 2 places in this library: (1) in extract queries and (2) flow queries.  Since each has its own id scheme (i.e. object ids are determined by the pagination process, not the underlying data) and we join data across extracts and flows, we need to ensure consistent usage.

FAI-5239: v2 flows not working

---

src/schema.ts
test/__snapshots__/schema.test.ts.snap
test/resources/schemas/timestamp-schema.gql
test/schema.test.ts

For `jsonb` fields, recursively replace epochs.  For purpose of this function, an epochs is a number with a property name that ends with 'At'.

FAI-6042: replace epochs with timestamps in jsonb fields

---

src/errors.ts
test/errors.test.ts

We encountered an situation where `wrapApiError` threw:
`[ERR_ASSERTION]: err must be an Error at Function.VError.cause `
This change handles that case by wrapping the non-Error.

Allow wrapApiError to support non-Errors

---

src/axios.ts
test/axios.test.ts

Deadlocks in Hasura will result in `HTTP 409` from GraphQL endpoint.  These should be retried automatically by `FarosClient`

FAI-6462: retry http 409 (edit conflict) for graphql endpoint

---

src/client.ts

Remove default limits on `axios` client

FAI-6878: compress graphql requests

---

src/client.ts
src/types.ts
test/client.test.ts

Add getWebhookEvent to faros client for use by Hermes lambda worker when an event body is omitted from the SQS message due to being too large. getWebhookEvent needs to be exposed in Hermes API as well, that will come as part of the PR to handle large event bodies

[FAI-7161] Add getWebhookEvent to faros client for use by Hermes lambda worker

---

package-lock.json
src/graphql/hasura-schema-loader.ts

Add support for list of scalars into table schema which were currently missing hence sources could not write lists
**Following fields now showing up:**
1. compute_ApplicationSource - repositoryPaths
2. faros_Path - parts
3. identity_Identity - emails
4. ims_Team - tags, teamChain
5. org_Employee - reportingChain
6. org_Team - tags, teamChain
7. qa_TestCase - tags
8. qa_TestExecution - environments, tags
9. qa_TestSuite - tags
10. tms_Team - tags, teamChain
11. vcs_Repository - topics
12. vcs_Team - tags, teamChain

FAI-7417: Add list type as scalars in table schema

---

src/client.ts
test/client.test.ts

For calling Faros API endpoints not exposed publicly, and more generally for calling any Faros API endpoint that doesn't currently have a provided client method.
> Fix [#1]() 

FAI-7137 - Add generic request method to client for calling internal endpoints

---

src/utils.ts
test/utils.test.ts

We do the conversion from `category: string` => `{category: SomeEnum.Symbol; detail: string}` very often in our codebase. In fact, I have three cases where this is needed just in [this](https://github.com/faros-ai/airbyte-connectors/pull/1170) PR
> Fix [#1]() 

Add category/details converter

---

src/utils.ts
test/utils.test.ts

Copied from [Hermes](https://github.com/faros-ai/hermes/blob/c0f3ca032486052b4fa7fcad1919084c2f783a0a/packages/worker/src/converters/utils.ts)
For reusability across our codebase
Ask me how I found this :D
> Fix [#1]() 

Move cleanAndTruncate from to Utils

---

src/graphql/graphql.ts
test/__snapshots__/graphql.test.ts.snap
test/graphql.test.ts
test/resources/schemas/schema-v2.gql

Use GraphQL schema hint (in the form of field `description` value of `array`) to indicate `jsonb` field contains array value.  This impacts the metadata produced by `flatten` utilities for our extract jobs.

FAI-9498: Support JSON Array with GraphQL Schema hint

---

src/graphql/graphql.ts
test/graphql.test.ts

Throw exception in `flattener` if root type is invalid

FAI-9931: Better error message for Invalid GraphQL type

---

src/graphql/graphql.ts
test/__snapshots__/graphql.test.ts.snap
test/resources/schemas/schema-v2.gql

Ensure that scalar array fields (e.g `text[]`) are included in incremental queries

FAI-9504: Include scalar arrays in incremental queries

---

src/graphql/graphql.ts
test/__snapshots__/graphql.test.ts.snap
test/graphql.test.ts

Add `scalarsOnly` option to exclude FKs queried as nested fragments.  They aren't needed for some use cases.
Prior behavior produced extra FKs like `pullRequestFk` in below:
```
query paginatedQuery($id: String, $limit: Int, $from: timestamptz!, $to: timestamptz!) {
vcs_PullRequestComment(
where: {_and: [{refreshedAt: {_gte: $from, _lt: $to}}, {id: {_gt: $id}}]}
order_by: {id: asc}
limit: $limit
) {
_id: id
id
author {
authorFk: id
}
authorId
comment
createdAt
isPhantom
number
origin
pullRequest {
pullRequestFk: id
}
pullRequestId
refreshedAt
updatedAt
}
} 
```
With `scalarsOnly` set to true, the output will be:
```
query paginatedQuery($id: String, $limit: Int, $from: timestamptz!, $to: timestamptz!) {
vcs_PullRequestComment(
where: {_and: [{refreshedAt: {_gte: $from, _lt: $to}}, {id: …
```

FAI-10363: Remove superfluous FKs from incremental queries

---

src/adapter/index.ts
src/client.ts
src/types.ts
test/adapter.test.ts
test/client.test.ts

Remove v1 logic from `FarosClient`
This is a breaking change

FAI-9741: Remove v1 support from FarosClient

---

package-lock.json
src/axios.ts
test/axios.test.ts

Allow having custom logic of when to retry instead of having a static value. User can then have logic for headers etc or whatever makes sense for their API

Support passing function for axios client delay

---

package-lock.json
package.json
src/date-format.d.ts
src/graphql/client/graphql-client.ts
src/graphql/client/graphql-writer.ts
src/graphql/client/types.ts
src/graphql/client/write-stats.ts
src/index.ts
test/.eslintrc.js
test/__snapshots__/graphql-client.test.ts.snap
test/graphql-client.test.ts
test/resources/hasura-ce-schema.json
test/resources/hasura-schema.json

Move `GraphGLClient` to `faros-js-client` so it can be used in both airbyte-connectors and Hermes.
It is needed in Hermes to improve performance of webhooks and user events.  See [here for details](https://docs.google.com/document/d/11BZVfhCD-R_rGoqmBejliW-94pHnLYHh8xemwTMXERQ/edit?tab=t.0#bookmark=id.4k5vbdyj6ycd) on the changes planned for Hermes.

FAI-14503: Batch Hermes GraphQL queries

---

src/graphql/client/graphql-client.ts
src/schema.ts

Two minor fixes that reduce time to run faros destination benchmark by 15%
```
tail -5 ~/baseline.small.log
real	1m3.201s
user	0m19.642s
sys	0m1.071s
$ tail -5 ~/fast.small.log
real	0m51.744s
user	0m16.478s
sys	0m1.171s
```
reduced user time by 15% (i.e. code excluding network calls)
1. don't use exceptions for flow control in `toDateAsISOString`
2. remove unnecessary copy and avoid `JSON.stringify` in assert in `objectWithForeignKeys`

FAI-14965: Fixed hotspots in faros destination
