faros-ai/faros-js-client

package-lock.json
package.json
src/client.ts
src/graphql/graphql.ts
src/graphql/types.ts
src/index.ts
test/__snapshots__/graphql.test.ts.snap
test/faros.test.ts
test/graphql.test.ts
test/helpers.ts
test/index.test.ts
test/resources/queries/commits-v2.gql
test/resources/queries/deployments.gql
test/resources/queries/incidents-v2.gql
test/resources/queries/max-node-depth.gql
test/resources/queries/multiple-selections.gql
test/resources/queries/mutation.gql
test/resources/queries/paginated-commits-v2.gql
test/resources/queries/paginated-deployments.gql
test/resources/queries/pull_request-v2.gql
test/resources/queries/tasks.gql
test/resources/schema-v2.gql
test/resources/schema.gql

Add graphql functionality
Note: The tests in `client.test.ts` and `faros.test.ts` both test `FarosClient`. We will migrate the latter into using `nock` and move into the same file in a separate PR.
> Fix [#1]() 

Add graphql functionality

---

src/graphql/graphql.ts
src/index.ts
test/__snapshots__/graphql.test.ts.snap
test/graphql.test.ts

Adds functions to convert queries into incremental
> Fix [#1]() 

Adds functions to convert query into incremental

---

src/client.ts
src/index.ts
src/types.ts
test/client.test.ts

Add get graph models to Faros client

---

src/client.ts

Fix error message

---

.tsconfig.json
scripts/load-schema.js
src/graphql/hasura-schema-loader.ts

Add support for serving PKs from GQL schema

FAI-4013: Hasura v3 Schema

---

src/client.ts

Import our `Location` type
> Fix [#1]() 

Use our Location type

---

src/client.ts
test/client.test.ts

Needed for [FAI-4507](https://faros-ai.atlassian.net/browse/FAI-4507)

Add method to get entry schema

---

src/graphql/hasura-schema-loader.ts

Log non-critical parse error to debug

Log non-critical parse error to debug

---

src/graphql/graphql.ts
test/__snapshots__/graphql.test.ts.snap
test/graphql.test.ts
test/helpers.ts
test/resources/v1_schema_for_embedded_test.gql

Handles embedded object fields and lists
> Fix [#1]() 

Handles embedded object fields and lists (V1 only)

---

src/schema.ts
test/schema.test.ts

Handle operation records in fixTimestampFields.
> Fix [#1]() 

Handle operation records in fixTimestampFields

---

src/client.ts
src/index.ts
src/types.ts

Exports `GraphVersion`
> Fix [#1]() 

Exports GraphVersion

---

package-lock.json
package.json
src/axios.ts

We should retry more network errors than just `ECONNABORTED`

Retry more network errors

---

src/client.ts
test/index.test.ts

Conditionally compress GraphQL requests

FAI-6878: Add GraphQL request compression

---

src/client.ts
src/index.ts
src/types.ts
test/client.test.ts

FAI-6888 - Add client method for updating webhook event status

---

src/types.ts
test/client.test.ts

FAI-6939 - Fix webhook event status body

---

src/client.ts
src/types.ts
test/client.test.ts

Add visibility query parameter support

FAI-6740: Metrics Pipeline - Visibility Type APIs

---

src/client.ts
test/client.test.ts

Use V2 graph api by default
> Fix [#1]() 

FAI-7358 Use V2 graph api by default

---

src/client.ts

FAI-7137 - Doc for generic request method

---

src/client.ts
test/client.test.ts

FAI-7137 - Add method to change api key of existing client

---

src/axios.ts
src/client.ts
test/axios.test.ts

Add type to Logger

---

package-lock.json
package.json

FAI-9026 - Update axios

---

src/graphql/graphql.ts

Make incremental explict metadata

FAI-3370: Incremental Deletes

---

src/index.ts

FAI-9951: Export phantom enum

---

src/client.ts
test/client.test.ts

FAI-9951: Add copy method to FarosClient

---

src/client.ts
src/types.ts
test/client.test.ts

Removing obsolete visibility feature

FAI-9501: Remove Clio visibility feature

---

src/graphql/graphql.ts
test/__snapshots__/graphql.test.ts.snap

Change incremental query `refreshedAt` predicate from 
```
_gte: new VariableType('from'),
_lt: new VariableType('to'),
```
to
```
_gt: new VariableType('from'),
_lte: new VariableType('to'),
```

FAI-13058: Incremental extract window based on data timestamps

---

package-lock.json
src/client.ts
test/client.test.ts

Get secret API is no longer offered, but we can still check for a secret existence.

FAI-12944 - Replace `secret` with `secretExists`

---

src/axios.ts

Add retryNumber as a parameter of delay function

---

src/graphql/graphql.ts
test/__snapshots__/graphql.test.ts.snap

Fix typo and revert incorrect change to snapshot

FAI-14934: Fix regression in graph copy

---

src/graphql/client/graphql-client.ts
test/graphql-client.test.ts

Log number of records marked for deletion vs number of records actually deleted.

FAI-15611 - Log records deleted

---

package-lock.json
package.json

FAI-15591 Upgrade axios => 1.8.3

---

.github/workflows/ci.yml
.github/workflows/release.yml
package-lock.json
package.json

FAI-16606 - Upgrade to node 22

---

package-lock.json

FAI-17471: Audit fix

---

.gitignore

Ignore .envrc for Devin GPG signing

Ignore .envrc (for devin)
